# Generated by Django 4.1.7 on 2023-03-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='month_reference',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], default='01'),
        ),
    ]
