# Generated by Django 4.1.7 on 2023-03-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_management', '0003_column_expense_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='column',
        ),
        migrations.AddField(
            model_name='column',
            name='column_type',
            field=models.CharField(choices=[('to_pay', 'A Pagar'), ('paid', 'Pago')], default='to_pay', max_length=10),
        ),
        migrations.AlterField(
            model_name='column',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
