# Generated by Django 4.1.7 on 2023-03-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_management', '0004_remove_expense_column_column_column_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='column',
            field=models.CharField(choices=[('PA', 'A pagar'), ('PG', 'Pago')], default='PA', max_length=20),
        ),
    ]
