# Generated by Django 4.1.7 on 2023-03-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_management', '0007_color_delete_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
